# railway.toml
[build]
builder = "nixpacks"

# railway.toml
[deploy]
startCommand = "python -c 'from test_railway_db import test_railway_connection; test_railway_connection()' && gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 wsgi:app"

[[services]]
name = "web"
type = "web"
httpPort = 8000