"""empty message

Revision ID: a9ce37dc777f
Revises: 92368f14e902
Create Date: 2025-08-11 00:36:28.320470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9ce37dc777f'
down_revision = '92368f14e902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('video')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
